-- AlterTable
ALTER TABLE `event` MODIFY `course` ENUM('ALL', 'ADS', 'GE', 'GTI', 'GEMP', 'MEC') NOT NULL,
    MODIFY `semester` ENUM('ALL', 'SEMESTER1', 'SEMESTER2', 'SEMESTER3', 'SEMESTER4', 'SEMESTER5', 'SEMESTER6', 'ESPECIAL') NULL;

-- AlterTable
ALTER TABLE `participant` MODIFY `course` ENUM('ALL', 'ADS', 'GE', 'GTI', 'GEMP', 'MEC') NULL,
    MODIFY `semester` ENUM('ALL', 'SEMESTER1', 'SEMESTER2', 'SEMESTER3', 'SEMESTER4', 'SEMESTER5', 'SEMESTER6', 'ESPECIAL') NULL;
