services:
  db_events-fatec-itu:
    image: mysql:8.0.42
    container_name: db_events-fatec-itu
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - db-data:/var/lib/mysql
      - ./prisma/init:/docker-entrypoint-initdb.d:ro
    ports:
      - '3307:3306'

  backend_events-fatec-itu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_events-fatec-itu
    restart: unless-stopped
    env_file:
      - .env.production
    depends_on:
      - db_events-fatec-itu
    ports:
      - '3001:3000'

volumes:
  db-data:

